const plainTokens: Record<string, string> = {
  durable_resumable_plan: "Durable resumable workspace plan",
  governed_workspace_budget: "Governed storage, retention, time, and disk budget",
  quality_labeled_provider_evidence: "Quality-labelled public and zero-fee provider evidence",
  receipt_bound_local_data: "Receipt-bound owned-file and portfolio data",
  verified_local_model_runtime: "Verified local model runtime",
  stopped_paper_under_central_risk: "Stopped paper account under central risk",
  verified_claude_code_mcp: "Separately verified Claude Code connection",
  verified_codex_mcp: "Separately verified Codex connection",
  verified_recovery_point: "Verified backup recovery point",
  capability_gap_review: "Capability and gap review",
  first_useful_result: "First useful owner result",
  none: "No additional input",
  local_confirmation: "Your explicit local confirmation",
  local_disk: "A local disk destination or budget",
  zero_fee_account_or_provider_key: "A zero-fee account or provider-issued key when required",
  owned_file: "A file you own, selected through the controlled picker",
  detected_local_client: "A supported local client detected by its owning adapter",
  coinbase_public_api: "Coinbase official public market-data API",
  kraken_public_api: "Kraken official public market-data API",
  securities_and_exchange_commission: "U.S. Securities and Exchange Commission",
  bureau_of_labor_statistics: "U.S. Bureau of Labor Statistics",
  united_states_treasury: "U.S. Treasury",
  federal_reserve_bank_of_st_louis: "Federal Reserve Bank of St. Louis (FRED/ALFRED)",
  claude_code_official_cli: "Installed Claude Code official CLI",
  codex_official_cli: "Installed Codex official CLI",
  accept_workspace_plan: "Record or replace the reversible workspace setup plan",
  configure_workspace_retention_and_budget: "Configure typed retention and disk-budget settings with rollback",
  activate_or_remove_provider_sessions: "Activate provider sessions that can later be stopped or removed",
  import_or_remove_derived_local_data: "Publish controlled imports whose derived local data can later be removed",
  configure_or_reset_model_runtime: "Configure or reset the installed model runtime",
  configure_stopped_paper_account_and_risk_defaults: "Configure stopped paper-only and central-risk defaults",
  register_or_disconnect_claude_code: "Register or disconnect one owned Claude Code entry",
  register_or_disconnect_codex: "Register or disconnect one owned Codex entry",
  create_or_remove_backup_policy: "Create, change, or remove the verified backup policy",
  no_additional_product_bytes: "No additional product bytes",
  variable_within_workspace_soft_limit: "Variable data within the workspace soft limit",
  variable_backup_destination: "Variable bytes at the approved backup destination",
  managed_workspace: "Managed local workspace",
  retention_and_disk_budget: "Retention and disk-budget controls",
  public_market_data: "Public market data",
  filing_research: "Filing research",
  macro_research: "Macro research",
  controlled_file_import: "Controlled owned-file import",
  portfolio_import: "Portfolio import and reconciliation",
  managed_python_runtime: "Managed Python research runtime",
  native_model_inference: "Native model inference",
  onnx_model_inference: "ONNX model inference",
  paper_only_execution: "Paper-only execution",
  central_risk: "Central risk authority",
  claude_code_mcp: "Claude Code MCP connection",
  codex_mcp: "Codex MCP connection",
  verified_backup: "Verified backup capability",
}

export function plainToken(value: string) {
  const known = plainTokens[value]
  if (known) return known
  const words = value.replaceAll("_", " ")
  return words.length > 0 ? `${words[0]!.toUpperCase()}${words.slice(1)}` : value
}
